apiVersion: apps/v1
kind: Deployment
metadata:
  name: arunjoshi-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    # app: arunjoshi-app
    matchExpressions:
      - key: app
        operator: In
        values: [arunjoshi-app]
  template:
    metadata:
      labels:
        app: arunjoshi-app
    spec:
      containers:
        - name: arunjoshi-node
          image: arunnjoshi/docker.k8:3
