apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: arunjoshi-app
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arunjoshi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arunjoshi-app
  template:
    metadata:
      labels:
        app: arunjoshi-app
    spec:
      containers:
        - name: arunjoshi-node
          image:
            arunnjoshi/docker.k8:3
            # ports:
            #   - containerPort: 80
