apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: arunjoshi-app
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arunjoshi-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arunjoshi-app
    # matchExpressions:
    #   - key: app
    #     operator: In
    #     values: [arunjoshi-app]
  template:
    metadata:
      labels:
        app: arunjoshi-app
    spec:
      containers:
        - name: arunjoshi-node
          image: arunnjoshi/docker.k8:8
          volumeMounts:
            - mountPath: /Data/
              name: text-file
          imagePullPolicy: Always
      volumes:
        - name: text-file
          persistentVolumeClaim:
            claimName: host-pvc
---
# host president volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Data/
    type: DirectoryOrCreate
# Host Claim volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
